apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
  - port: 8091
    targetPort: 8080
    name: http
  selector:
    app: cicd
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
spec:
  replicas: 3 #It tells how PODs to be created to maintain HA
  selector:
    app: cicd
  template:
    metadata:
      name: jenkins-cicd
      labels:
        app: cicd
    spec:
      containers:
      - name: jenkins-server
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-data
      volumes:
        - name: jenkins-data
          nfs:
            server: 192.168.1.120
            path: /var/jenkins_data