apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: NodePort
  ports:
  - port: 8091
    targetPort: 80
    name: http
  selector:
    app: test-app
---
apiVersion: apps/v1 #extensions/v1beta1 for before v1.16
kind: ReplicaSet
metadata:
  name: test-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80
        volumeMounts:
         - mountPath: /usr/share/nginx/html
           name: web-data
      volumes:
        - name: web-data
          nfs:
            server: 192.168.1.120
            path: /var/nginx_data